use persistencepractise;
delete from driver;
insert into driver(iddriver, firstname, lastname, cost) values(0, "Lewis", "Hamilton", 8000000);
insert into driver(iddriver, firstname, lastname, cost) values(1, "Sebastian", "Vettel", 8000000);
insert into driver(iddriver, firstname, lastname, cost) values(2, "Kimi", "Raikkonnen", 8000000);
insert into driver(iddriver, firstname, lastname, cost) values(3, "Max", "Verstappen", 8000000);
insert into driver(iddriver, firstname, lastname, cost) values(4, "Valtteri", "Bottas", 5000000);
insert into driver(iddriver, firstname, lastname, cost) values(5, "Daniel", "Ricciardo", 5000000);
insert into driver(iddriver, firstname, lastname, cost) values(6, "Nico", "Hulkenberg", 5000000);
insert into driver(iddriver, firstname, lastname, cost) values(7, "Sergio", "Perez", 5000000);
insert into driver(iddriver, firstname, lastname, cost) values(8, "Kevin", "Magnussen", 3000000);
insert into driver(iddriver, firstname, lastname, cost) values(9, "Carlos", "Sainz", 3000000);
insert into driver(iddriver, firstname, lastname, cost) values(10, "Fernando", "Alonso", 3000000);
insert into driver(iddriver, firstname, lastname, cost) values(11, "Esteban", "Ocon", 3000000);
insert into driver(iddriver, firstname, lastname, cost) values(12, "Charles", "Leclerc", 2000000);
insert into driver(iddriver, firstname, lastname, cost) values(13, "Romain", "Grosjean", 2000000);
insert into driver(iddriver, firstname, lastname, cost) values(14, "Pierre", "Gasly", 2000000);
insert into driver(iddriver, firstname, lastname, cost) values(15, "Stoffel", "Vandoorne", 2000000);
insert into driver(iddriver, firstname, lastname, cost) values(16, "Marcus", "Ericsson", 2000000);
insert into driver(iddriver, firstname, lastname, cost) values(17, "Lance", "Stroll", 2000000);
insert into driver(iddriver, firstname, lastname, cost) values(18, "Brendon", "Hartley", 2000000);
insert into driver(iddriver, firstname, lastname, cost) values(19, "Sergey", "Sirotkin", 2000000);
Select * from driver;